# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    # docker compose -p hoidanit-nest up -d
